version: '2.1'
services:
  api:
    build: .
    command: sh test.sh
    env_file:
      - test.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: basket_password
      POSTGRES_USER: basket_user
      POSTGRES_DB: basket_db

