name:  Docker Compose Test And Push
on: 
  push:
    branches:
    - main
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute tests
        run: docker-compose -f docker-compose.test.yml up --exit-code-from api --build
      - name: Push to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fabian818/checkout-basket-api
          tags: latest, "${GITHUB_SHA}" 
