name: Docker Compose Test Workflow
on: 
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: execute tests
        run: docker-compose -f docker-compose.test.yml up --exit-code-from api --build
